#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

## {{ Set up error handler.
if [ "$(type -t errorhandlergeneral)" = "function" ]; then
   ## Function errorhandlergeneral exists (declared in
   ## help-steps/pre). Prefer to use the more feature rich version of the error
   ## handler.
   trap "errorhandlergeneral" ERR
else
   ## Function errorhandlergeneral does not exist. Script
   ## runs standalone outside the build script. Fall back to a simpler error
   ## handler.
   trap "error_handler" ERR
fi
## }}

own_filename="$(basename "$BASH_SOURCE")"
for skip_script in $SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

## just another backup
mkdir --parents /var/lib/anon-dist/grub-backup

if [ "$CI" = "true" ]; then
   true "INFO $BASH_SOURCE: Skipping, because CI detected."
else
   ## Non-deterministic on Debian Wheezy. Should work on Debian Jessie.
   #cp /boot/grub/grub.cfg /var/lib/anon-dist/grub-backup/grub.cfg.chroot-post3
   true
fi

## Installation of 486 kernel (in chroot-scripts-post.d 70_install_486_kernel)
## might have run update-grub (as part of its postinst script) and
## the 85_update_grub chroot-scripts-post.d script runs update-grub to let changes in
## /etc/default/grub take effect.
## grub has a bug to mess up /boot/grub/grub.cfg when run inside chroot
## (which will get fixed in grub 2.something).
## Therefore we have to fix it here.

if [ "$ANON_BUILD_INSTALL_TO_ROOT" = "1" ]; then
   true "INFO $BASH_SOURCE: Fixing /boot/grub/grub.cfg is not required for bare metal builds (ANON_BUILD_INSTALL_TO_ROOT is set to 1), skipping."
else
   if [ "$CI" = "true" ]; then
      true "INFO $BASH_SOURCE: Skipping, because CI detected."
   else
      true "INFO $BASH_SOURCE: Fixing /boot/grub/grub.cfg to work around a bug in grub when run inside chroot..."

      if [ "$DISK_IDENTIFIER" = "" ]; then
         DISK_IDENTIFIER='26ada0c0-1165-4098-884d-aafd2220c2c6'
      fi

      ## For the following two lines, credit goes to grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
      ## It's taken from usr/sbin/grml-debootstrap, from grml-debootstrap package, which is licensed GPL v2+.
      #sed -i "s;set root=.*;set root='(hd0,msdos1)';" /boot/grub/grub.cfg
      #sed -i "s;root=[^ ]\+;root=/dev/sda1;" /boot/grub/grub.cfg
      ## Adjusted for Whonix.
      sed -i "s;root=[^ ]\+;root=UUID=$DISK_IDENTIFIER;" /boot/grub/grub.cfg

      true "INFO $BASH_SOURCE: Fixed /boot/grub/grub.cfg."

      true "INFO $BASH_SOURCE: Deleting /boot/grub/device.map..."
      rm --force "/boot/grub/device.map"
      true "INFO $BASH_SOURCE: Deleted /boot/grub/device.map."
   fi
fi

## just another backup
mkdir --parents /var/lib/anon-dist/grub-backup

if [ "$CI" = "true" ]; then
   true "INFO $BASH_SOURCE: Skipping, because CI detected."
else
   cp /boot/grub/grub.cfg /var/lib/anon-dist/grub-backup/grub.cfg.chroot-post4
fi

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
